# Hold the target item in your off hand, then use each blessing from the main hand.
give @s matcha:blessing_bane_of_arthopods 1
give @s matcha:blessing_channeling_smite 1
give @s matcha:blessing_density_knockback_punch 1
give @s matcha:blessing_depth_strider_riptide_aqua_affinity_respiration 1
give @s matcha:blessing_efficiency_unbreaking 1
give @s matcha:blessing_feather_falling 1
give @s matcha:blessing_flame_fire_aspect_fire_protection 1
give @s matcha:blessing_frost_walker_frost_protection 1
give @s matcha:blessing_hell_bound_book 1
give @s matcha:blessing_infinity 1
give @s matcha:blessing_lunge_breach 1
give @s matcha:blessing_lure_luck_of_the_sea 1
give @s matcha:blessing_mending 1
give @s matcha:blessing_piercing_impaling 1
give @s matcha:blessing_power_multishot 1
give @s matcha:blessing_reach 1
give @s matcha:blessing_silk_touch 1
give @s matcha:blessing_swift_sneak_soul_speed 1
give @s matcha:blessing_traversal 1
give @s matcha:blessing_unbreaking 1
give @s matcha:blessing_warding 1
give @s matcha:blessing_wind_burst_anemos 1
give @s matcha:blessing_zephyr 1
