# Generated equipment parity test kit
give @s matcha:adamant_axe 1
give @s matcha:adamant_boots 1
give @s matcha:adamant_chestplate 1
give @s matcha:adamant_claymore 1
give @s matcha:adamant_dolabra 1
give @s matcha:adamant_helmet 1
give @s matcha:adamant_hoe 1
give @s matcha:adamant_leggings 1
give @s matcha:adamant_mattock 1
give @s matcha:adamant_pickaxe 1
give @s matcha:adamant_shovel 1
give @s matcha:adamant_spear 1
give @s matcha:adamant_sword 1
give @s matcha:bronze_axe 1
give @s matcha:bronze_pickaxe 1
give @s matcha:bronze_shovel 1
give @s matcha:bronze_hoe 1
give @s matcha:bronze_spear 1
give @s matcha:bronze_mattock 1
give @s matcha:bronze_dolabra 1
give @s matcha:bronze_shears 1
give @s matcha:bronze_helmet 1
give @s matcha:bronze_chestplate 1
give @s matcha:bronze_leggings 1
give @s matcha:bronze_boots 1
give @s matcha:electrum_axe 1
give @s matcha:electrum_boots 1
give @s matcha:electrum_chestplate 1
give @s matcha:electrum_dolabra 1
give @s matcha:electrum_helmet 1
give @s matcha:electrum_hoe 1
give @s matcha:electrum_leggings 1
give @s matcha:electrum_mattock 1
give @s matcha:electrum_pickaxe 1
give @s matcha:electrum_shovel 1
give @s matcha:electrum_spear 1
give @s matcha:electrum_sword 1
give @s matcha:shakudo_axe 1
give @s matcha:shakudo_boots 1
give @s matcha:shakudo_chestplate 1
give @s matcha:shakudo_dolabra 1
give @s matcha:shakudo_helmet 1
give @s matcha:shakudo_hoe 1
give @s matcha:shakudo_leggings 1
give @s matcha:shakudo_mattock 1
give @s matcha:shakudo_pickaxe 1
give @s matcha:shakudo_shovel 1
give @s matcha:shakudo_spear 1
give @s matcha:shakudo_sword 1
give @s matcha:steel_axe 1
give @s matcha:steel_boots 1
give @s matcha:steel_chestplate 1
give @s matcha:steel_dolabra 1
give @s matcha:steel_helmet 1
give @s matcha:steel_hoe 1
give @s matcha:steel_leggings 1
give @s matcha:steel_mattock 1
give @s matcha:steel_pickaxe 1
give @s matcha:steel_shears 1
give @s matcha:steel_shovel 1
give @s matcha:steel_spear 1
give @s matcha:steel_sword 1
give @s minecraft:anvil 1
give @s minecraft:smithing_table 1
