# Generated consumables test kit
give @s matcha:apple_empanada 1
give @s matcha:baked_apple 1
give @s matcha:baked_golden_apple 1
give @s matcha:baked_potato 1
give @s matcha:baked_pumpkin 1
give @s matcha:bokguk 1
give @s matcha:braised_brown_mushroom 1
give @s matcha:braised_crimson_fungus 1
give @s matcha:braised_red_mushroom 1
give @s matcha:braised_warped_fungus 1
give @s matcha:bread 1
give @s matcha:brownie 1
give @s matcha:bruschetta 1
give @s matcha:canned_apples 1
give @s matcha:canned_golden_apples 1
give @s matcha:carrot_cupcake 1
give @s matcha:charred_fish 1
give @s matcha:charred_meat 1
give @s matcha:charred_potato 1
give @s matcha:cheese 1
give @s matcha:chocolate 1
give @s matcha:chocolate_chip_cookie 1
give @s matcha:chorus_mochi 1
give @s matcha:cooked_beef 1
give @s matcha:cooked_chicken 1
give @s matcha:cooked_cod 1
give @s matcha:cooked_mutton 1
give @s matcha:cooked_porkchop 1
give @s matcha:cooked_pufferfish 1
give @s matcha:cooked_rabbit 1
give @s matcha:cooked_salmon 1
give @s matcha:crafting_chicken_noodle_soup 1
give @s matcha:crafting_golden_pie 1
give @s matcha:crafting_green_curry 1
give @s matcha:crafting_morsel_stew 1
give @s matcha:crafting_paneer_makhani 1
give @s matcha:crafting_ramen 1
give @s matcha:crafting_squid_ink_pasta 1
give @s matcha:crafting_stuffed_mushrooms 1
give @s matcha:crimson_stroganoff 1
give @s matcha:dried_kelp 1
give @s matcha:dried_kelp_from_dried_kelp_block 1
give @s matcha:french_toast 1
give @s matcha:fried_egg 1
give @s matcha:gimmari 1
give @s matcha:glow_berry_crumble 1
give @s matcha:glow_jam 1
give @s matcha:glow_mash 1
give @s matcha:gnocchi 1
give @s matcha:golden_apple 1
give @s matcha:golden_apple_empanada 1
give @s matcha:golden_carrot 1
give @s matcha:golden_carrot_cupcake 1
give @s matcha:golden_pickled_carrots 1
give @s matcha:golden_steamed_carrots 1
give @s matcha:green_curry 1
give @s matcha:grilled_melon 1
give @s matcha:grilled_tomatoes 1
give @s matcha:honey_ginger_tea 1
give @s matcha:honied_french_toast 1
give @s matcha:japanese_curry 1
give @s matcha:latke 1
give @s matcha:mead 1
give @s matcha:melon_sorbet 1
give @s matcha:milk_bottle 1
give @s matcha:naan 1
give @s matcha:paneer_makhani 1
give @s matcha:pickled_carrots 1
give @s matcha:pickled_crimson_fungus 1
give @s matcha:pickled_mushrooms 1
give @s matcha:pickled_potatoes 1
give @s matcha:pickled_red_mushrooms 1
give @s matcha:pickled_tomatoes 1
give @s matcha:pickled_warped_fungus 1
give @s matcha:popped_chorus_fruit 1
give @s matcha:potions_estus_flask 1
give @s matcha:puerquito 1
give @s matcha:pumpkin_empanada 1
give @s matcha:pumpkin_jam 1
give @s matcha:pupusa 1
give @s matcha:ramen 1
give @s matcha:red_mushroom_stroganoff 1
give @s matcha:rind_jam 1
give @s matcha:steamed_carrots 1
give @s matcha:stroganoff 1
give @s matcha:sweet_berry_danish 1
give @s matcha:sweet_berry_jam 1
give @s matcha:sweet_berry_mash 1
give @s matcha:sweet_berry_toast 1
give @s matcha:warped_stroganoff 1
