# Generated component-item test kit
give @s matcha:amnestic 1
give @s matcha:bedrock_buster 1
give @s matcha:benzene 1
give @s matcha:campfire 1
give @s matcha:carbon_rich_iron 1
give @s matcha:chainmail_boots 1
give @s matcha:chainmail_chestplate 1
give @s matcha:chainmail_helmet 1
give @s matcha:chainmail_leggings 1
give @s matcha:copper_axe 1
give @s matcha:copper_boots 1
give @s matcha:copper_chestplate 1
give @s matcha:copper_compass 1
give @s matcha:copper_dolabra 1
give @s matcha:copper_helmet 1
give @s matcha:copper_hoe 1
give @s matcha:copper_leggings 1
give @s matcha:copper_mattock 1
give @s matcha:copper_pickaxe 1
give @s matcha:copper_shears 1
give @s matcha:copper_shovel 1
give @s matcha:copper_spear 1
give @s matcha:copper_sword 1
give @s matcha:diamond_axe 1
give @s matcha:diamond_boots 1
give @s matcha:diamond_chestplate 1
give @s matcha:diamond_dolabra 1
give @s matcha:diamond_helmet 1
give @s matcha:diamond_hoe 1
give @s matcha:diamond_leggings 1
give @s matcha:diamond_mattock 1
give @s matcha:diamond_pickaxe 1
give @s matcha:diamond_shovel 1
give @s matcha:diamond_spear 1
give @s matcha:diamond_sword 1
give @s matcha:divine_fragment 1
give @s matcha:golden_axe 1
give @s matcha:golden_boots 1
give @s matcha:golden_chestplate 1
give @s matcha:golden_compass 1
give @s matcha:golden_helmet 1
give @s matcha:golden_hoe 1
give @s matcha:golden_leggings 1
give @s matcha:golden_pickaxe 1
give @s matcha:golden_shovel 1
give @s matcha:golden_spear 1
give @s matcha:golden_sword 1
give @s matcha:invisible_item_frame 1
give @s matcha:iron_axe 1
give @s matcha:iron_boots 1
give @s matcha:iron_chestplate 1
give @s matcha:iron_dolabra 1
give @s matcha:iron_helmet 1
give @s matcha:iron_hoe 1
give @s matcha:iron_leggings 1
give @s matcha:iron_mattock 1
give @s matcha:iron_pickaxe 1
give @s matcha:iron_shears 1
give @s matcha:iron_shovel 1
give @s matcha:iron_spear 1
give @s matcha:iron_sword 1
give @s matcha:leather_boots 1
give @s matcha:leather_chestplate 1
give @s matcha:leather_helmet 1
give @s matcha:leather_pants 1
give @s matcha:mace 1
give @s matcha:minecart_from_steel 1
give @s matcha:music_disc_golden 1
give @s matcha:nazar 1
give @s matcha:snow_shovel 1
give @s matcha:soul_campfire 1
give @s matcha:stabilised_estus 1
give @s matcha:sturdy_leather_boots 1
give @s matcha:sturdy_leather_chestplate 1
give @s matcha:sturdy_leather_helmet 1
give @s matcha:sturdy_leather_pants 1
give @s matcha:tinder 1
give @s matcha:warding_stone 1
give @s matcha:wooden_axe 1
give @s matcha:wooden_cross 1
give @s matcha:wooden_hoe 1
give @s matcha:wooden_pickaxe 1
give @s matcha:wooden_shovel 1
give @s matcha:wooden_spear 1
give @s matcha:wooden_sword 1
give @s matcha:music_disc_labyrinthine 1
give @s matcha:cake 1
give @s matcha:dough 1
give @s matcha:dough_from_water 1
give @s matcha:flour 1
give @s matcha:flour_bag 1
give @s matcha:flour_from_flour_bag 1
give @s matcha:uncooked_curry 1
give @s matcha:uncooked_green_curry 1
give @s matcha:uncooked_paneer_makhani 1
give @s matcha:uncooked_ramen 1
give @s matcha:amber_earrings 1
give @s matcha:bronze_elytra 1
give @s matcha:butcher_knife 1
give @s matcha:gilded_leather_boots 1
give @s matcha:lesser_warding_shield 1
give @s matcha:silver_sword 1
give @s matcha:warding_shield 1
give @s matcha:warding_sword 1
