// Generated by tools/convert_worldgen.py. Do not edit by hand.
export const BIOME_AMBIENCE = {
  "minecraft:basalt_deltas": {
    "particle": "white_ash",
    "particleChance": 0.118093334,
    "loop": "ambient.basalt_deltas.loop",
    "addition": "ambient.basalt_deltas.additions",
    "additionChance": 0.0111,
    "mood": "ambient.basalt_deltas.mood",
    "moodDelay": 6000
  },
  "minecraft:crimson_forest": {
    "particle": "crimson_spore",
    "particleChance": 0.015,
    "loop": "ambient.crimson_forest.loop",
    "addition": "ambient.crimson_forest.additions",
    "additionChance": 0.0111,
    "mood": "ambient.crimson_forest.mood",
    "moodDelay": 6000
  },
  "minecraft:deep_frozen_ocean": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:frozen_ocean": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:frozen_peaks": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:frozen_river": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:grove": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:ice_spikes": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:jagged_peaks": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:nether_wastes": {
    "loop": "ambient.nether_wastes.loop",
    "addition": "ambient.nether_wastes.additions",
    "additionChance": 0.0111,
    "mood": "ambient.nether_wastes.mood",
    "moodDelay": 6000
  },
  "minecraft:snowy_beach": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:snowy_plains": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:snowy_slopes": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:snowy_taiga": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  },
  "minecraft:soul_sand_valley": {
    "particle": "ash",
    "particleChance": 0.00625,
    "loop": "ambient.soul_sand_valley.loop",
    "addition": "ambient.soul_sand_valley.additions",
    "additionChance": 0.0111,
    "mood": "ambient.soul_sand_valley.mood",
    "moodDelay": 6000
  },
  "minecraft:warped_forest": {
    "particle": "warped_spore",
    "particleChance": 0.01428,
    "loop": "ambient.warped_forest.loop",
    "addition": "ambient.warped_forest.additions",
    "additionChance": 0.0111,
    "mood": "ambient.warped_forest.mood",
    "moodDelay": 6000
  },
  "minecraft:windswept_gravelly_hills": {
    "particle": "white_ash",
    "particleChance": 0.00376167
  }
};
