// Generated by tools/generate_enchantments.py; do not edit.
export const BLESSINGS = {
  "matcha:blessing_bane_of_arthopods": {
    "minecraft:bane_of_arthropods": 5
  },
  "matcha:blessing_channeling_smite": {
    "minecraft:channeling": 1,
    "minecraft:smite": 3
  },
  "matcha:blessing_density_knockback_punch": {
    "minecraft:density": 2,
    "minecraft:knockback": 2,
    "minecraft:punch": 2
  },
  "matcha:blessing_depth_strider_riptide_aqua_affinity_respiration": {
    "minecraft:aqua_affinity": 1,
    "minecraft:depth_strider": 2,
    "minecraft:respiration": 2,
    "minecraft:riptide": 1
  },
  "matcha:blessing_efficiency_unbreaking": {
    "minecraft:efficiency": 3,
    "minecraft:unbreaking": 3
  },
  "matcha:blessing_feather_falling": {
    "minecraft:feather_falling": 2
  },
  "matcha:blessing_flame_fire_aspect_fire_protection": {
    "minecraft:fire_aspect": 1,
    "minecraft:fire_protection": 3,
    "minecraft:flame": 1
  },
  "matcha:blessing_frost_walker_frost_protection": {
    "main:freezing_protection": 2,
    "minecraft:frost_walker": 2
  },
  "matcha:blessing_hell_bound_book": {
    "minecraft:binding_curse": 1
  },
  "matcha:blessing_infinity": {
    "minecraft:infinity": 1
  },
  "matcha:blessing_lunge_breach": {
    "minecraft:breach": 2,
    "minecraft:lunge": 2
  },
  "matcha:blessing_lure_luck_of_the_sea": {
    "minecraft:loyalty": 1,
    "minecraft:luck_of_the_sea": 3,
    "minecraft:lure": 3
  },
  "matcha:blessing_mending": {
    "minecraft:mending": 1
  },
  "matcha:blessing_piercing_impaling": {
    "minecraft:impaling": 3,
    "minecraft:piercing": 2
  },
  "matcha:blessing_power_multishot": {
    "minecraft:multishot": 1,
    "minecraft:power": 2
  },
  "matcha:blessing_reach": {
    "main:reach": 1
  },
  "matcha:blessing_silk_touch": {
    "minecraft:silk_touch": 1
  },
  "matcha:blessing_swift_sneak_soul_speed": {
    "minecraft:soul_speed": 2,
    "minecraft:swift_sneak": 2
  },
  "matcha:blessing_traversal": {
    "main:traversal": 3
  },
  "matcha:blessing_unbreaking": {
    "minecraft:unbreaking": 2
  },
  "matcha:blessing_warding": {
    "main:warding2": 1,
    "minecraft:smite": 2
  },
  "matcha:blessing_wind_burst_anemos": {
    "main:anemos": 1,
    "minecraft:wind_burst": 3
  },
  "matcha:blessing_zephyr": {
    "main:zephyr": 1
  }
};
export const EQUIPMENT_ENCHANTMENTS = {
  "matcha:adamant_axe": [
    "divinity"
  ],
  "matcha:adamant_boots": [
    "divinity"
  ],
  "matcha:adamant_chestplate": [
    "divinity"
  ],
  "matcha:adamant_claymore": [
    "divinity"
  ],
  "matcha:adamant_dolabra": [
    "divinity"
  ],
  "matcha:adamant_helmet": [
    "divinity"
  ],
  "matcha:adamant_hoe": [
    "divinity"
  ],
  "matcha:adamant_leggings": [
    "divinity"
  ],
  "matcha:adamant_mattock": [
    "divinity"
  ],
  "matcha:adamant_pickaxe": [
    "divinity"
  ],
  "matcha:adamant_shovel": [
    "divinity"
  ],
  "matcha:adamant_spear": [
    "divinity"
  ],
  "matcha:adamant_sword": [
    "divinity"
  ],
  "matcha:electrum_axe": [
    "warding2"
  ],
  "matcha:electrum_boots": [
    "warding_armour"
  ],
  "matcha:electrum_chestplate": [
    "warding_armour"
  ],
  "matcha:electrum_dolabra": [
    "warding1"
  ],
  "matcha:electrum_helmet": [
    "warding_armour"
  ],
  "matcha:electrum_hoe": [
    "warding1"
  ],
  "matcha:electrum_leggings": [
    "warding_armour"
  ],
  "matcha:electrum_mattock": [
    "warding1"
  ],
  "matcha:electrum_pickaxe": [
    "warding1"
  ],
  "matcha:electrum_shovel": [
    "warding1"
  ],
  "matcha:electrum_spear": [
    "warding2"
  ],
  "matcha:electrum_sword": [
    "warding2"
  ],
  "matcha:shakudo_boots": [
    "cleanse_armor_feet"
  ],
  "matcha:shakudo_chestplate": [
    "cleanse_armor_chest"
  ],
  "matcha:shakudo_helmet": [
    "cleanse_armor_head"
  ],
  "matcha:shakudo_leggings": [
    "cleanse_armor_legs"
  ],
  "matcha:shakudo_spear": [
    "sanguine"
  ],
  "matcha:shakudo_sword": [
    "sanguine"
  ],
  "matcha:nazar": [
    "warding1"
  ],
  "matcha:sturdy_leather_boots": [
    "traversal"
  ],
  "matcha:wooden_cross": [
    "warding0"
  ],
  "matcha:amber_earrings": [
    "regeneration"
  ],
  "matcha:butcher_knife": [
    "slaughter"
  ],
  "matcha:silver_sword": [
    "warding0"
  ],
  "matcha:warding_shield": [
    "warding1"
  ],
  "matcha:warding_sword": [
    "warding0"
  ]
};
