// Generated by tools/convert_foods.py. Do not edit by hand.
export const FOOD_EFFECTS = {
  "matcha:crafting_chicken_noodle_soup": [
    {
      "type": "remove_effects",
      "effects": [
        "blindness",
        "mining_fatigue",
        "nausea",
        "bad_omen",
        "darkness",
        "infested",
        "oozing",
        "poison",
        "slowness",
        "unluck",
        "weakness",
        "weaving",
        "wind_charged",
        "wither"
      ]
    },
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "saturation",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_golden_pie": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 200,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "absorption",
          "duration": 2400,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_green_curry": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "saturation",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "speed",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "haste",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_morsel_stew": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "saturation",
          "duration": 2400,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_paneer_makhani": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "saturation",
          "duration": 2400,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_ramen": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_squid_ink_pasta": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "saturation",
          "duration": 2400,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crafting_stuffed_mushrooms": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:apple_empanada": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 3600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:baked_apple": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:baked_golden_apple": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "absorption",
          "duration": 2400,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:baked_potato": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 60,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:baked_pumpkin": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "resistance",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:bokguk": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "conduit_power",
          "duration": 9600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 144,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:braised_brown_mushroom": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:braised_crimson_fungus": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "weakness",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:braised_red_mushroom": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "poison",
          "duration": 600,
          "amplifier": 0,
          "showParticles": true
        }
      ]
    }
  ],
  "matcha:braised_warped_fungus": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "invisibility",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:bread": [
    {
      "type": "remove_effects",
      "effects": [
        "poison",
        "mining_fatigue",
        "wither",
        "weakness",
        "bad_omen",
        "blindness",
        "darkness",
        "infested",
        "weaving",
        "nausea",
        "oozing",
        "slowness"
      ]
    },
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:brownie": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 72,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "haste",
          "duration": 3000,
          "amplifier": 1,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:bruschetta": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "strength",
          "duration": 3000,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:canned_apples": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 72,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:canned_golden_apples": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 400,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "absorption",
          "duration": 2400,
          "amplifier": 1,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:carrot_cupcake": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "night_vision",
          "duration": 12000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:charred_fish": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 15,
          "amplifier": 3,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:charred_meat": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 15,
          "amplifier": 3,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:charred_potato": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 20,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cheese": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 36,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:chocolate": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "haste",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:chocolate_chip_cookie": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "haste",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:chorus_mochi": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "levitation",
          "duration": 20,
          "amplifier": 29,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_beef": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_chicken": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_cod": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_mutton": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_porkchop": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_pufferfish": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "conduit_power",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_rabbit": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:cooked_salmon": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 60,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:crimson_stroganoff": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "weakness",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 144,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:dried_kelp": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 12,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "water_breathing",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:french_toast": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 120,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:fried_egg": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:gimmari": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "water_breathing",
          "duration": 9600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 72,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:glow_berry_crumble": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:glow_jam": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:glow_mash": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:gnocchi": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 192,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:golden_apple": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "absorption",
          "duration": 2400,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:golden_apple_empanada": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 900,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "absorption",
          "duration": 4800,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": true
        }
      ]
    }
  ],
  "matcha:golden_carrot": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "night_vision",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:golden_carrot_cupcake": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "night_vision",
          "duration": 24000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:golden_pickled_carrots": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "night_vision",
          "duration": 12000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:golden_steamed_carrots": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 15,
          "amplifier": 3,
          "showParticles": false
        },
        {
          "id": "night_vision",
          "duration": 1200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:green_curry": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 240,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "speed",
          "duration": 36000,
          "amplifier": 1,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:grilled_melon": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "fire_resistance",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:grilled_tomatoes": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "strength",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:honey_ginger_tea": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "speed",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    },
    {
      "type": "remove_effects",
      "effects": [
        "poison",
        "mining_fatigue",
        "wither",
        "weakness",
        "bad_omen",
        "blindness",
        "darkness",
        "infested",
        "weaving",
        "nausea",
        "oozing",
        "slowness"
      ]
    }
  ],
  "matcha:honied_french_toast": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "speed",
          "duration": 3600,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 120,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:japanese_curry": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 240,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "strength",
          "duration": 36000,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:latke": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 192,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:mead": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "speed",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 72,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:melon_sorbet": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "fire_resistance",
          "duration": 12000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:milk_bottle": [
    {
      "type": "clear_all_effects"
    }
  ],
  "matcha:naan": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 15,
          "amplifier": 3,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:paneer_makhani": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 240,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 12000,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pickled_carrots": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "night_vision",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pickled_crimson_fungus": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "weakness",
          "duration": 1200,
          "amplifier": 1,
          "showParticles": true
        }
      ]
    }
  ],
  "matcha:pickled_mushrooms": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 72,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pickled_potatoes": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "resistance",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 120,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pickled_red_mushrooms": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "poison",
          "duration": 1200,
          "amplifier": 1,
          "showParticles": true
        }
      ]
    }
  ],
  "matcha:pickled_tomatoes": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "strength",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 72,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pickled_warped_fungus": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "invisibility",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:popped_chorus_fruit": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "levitation",
          "duration": 60,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:puerquito": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pumpkin_empanada": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "resistance",
          "duration": 9600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pumpkin_jam": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "resistance",
          "duration": 3600,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:pupusa": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 36,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:ramen": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 240,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "haste",
          "duration": 36000,
          "amplifier": 1,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:red_mushroom_stroganoff": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "poison",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 144,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:rind_jam": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "fire_resistance",
          "duration": 6000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:steamed_carrots": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "night_vision",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:stroganoff": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 192,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:sweet_berry_danish": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "health_boost",
          "duration": 9600,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 96,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:sweet_berry_jam": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "regeneration",
          "duration": 48,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "health_boost",
          "duration": 3600,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:sweet_berry_mash": [
    {
      "type": "apply_effects",
      "probability": 1,
      "effects": [
        {
          "id": "regeneration",
          "duration": 24,
          "amplifier": 2,
          "showParticles": false
        },
        {
          "id": "health_boost",
          "duration": 200,
          "amplifier": 0,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:sweet_berry_toast": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "health_boost",
          "duration": 9600,
          "amplifier": 1,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 120,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:warped_stroganoff": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "invisibility",
          "duration": 12000,
          "amplifier": 0,
          "showParticles": false
        },
        {
          "id": "regeneration",
          "duration": 144,
          "amplifier": 2,
          "showParticles": false
        }
      ]
    }
  ],
  "matcha:potions_estus_flask": [
    {
      "type": "apply_effects",
      "effects": [
        {
          "id": "instant_health",
          "duration": 1,
          "amplifier": 1,
          "showParticles": false
        }
      ]
    }
  ]
};
