// Generated by tools/convert_foods.py. Do not edit by hand.
export const SPLASH_FOODS = {
  "matcha:pickled_crimson_fungus": [{
    "type": "apply_effects",
    "effects": [{"id": "weakness", "duration": 1200, "amplifier": 1, "showParticles": true}]
  }],
  "matcha:pickled_red_mushrooms": [{
    "type": "apply_effects",
    "effects": [{"id": "poison", "duration": 1200, "amplifier": 1, "showParticles": true}]
  }]
};
