#!/usr/bin/env python3
"""Generate Bedrock blessing proxies and the custom-enchantment effect map."""
import argparse, json, shutil
from pathlib import Path
from convert_recipes import convert, safe_name
from upstream import add_source_argument, baseline, validate_source

ROOT=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(); add_source_argument(parser)
JAVA=validate_source(parser.parse_args().source)
ITEMS=ROOT/"behavior_pack/items/generated_blessings"
RECIPES=ROOT/"behavior_pack/recipes/generated_blessings"
TEXTURES=ROOT/"resource_pack/textures/items/generated_blessings"
ATLAS=ROOT/"resource_pack/textures/item_texture.json"
LANG=ROOT/"resource_pack/texts/en_US.lang"
for directory in (ITEMS,RECIPES,TEXTURES):
    directory.mkdir(parents=True,exist_ok=True)
    for path in directory.iterdir():
        if path.is_file(): path.unlink()

atlas=json.loads(ATLAS.read_text()); atlas["texture_data"]={k:v for k,v in atlas["texture_data"].items() if not k.startswith("matcha_blessing_")}
source_lang=json.loads((JAVA/"assets/minecraft/lang/en_us.json").read_text())
blessings={}; lang=[]
for path in sorted((JAVA/"data/blessings/recipe").glob("*.json")):
    source=json.loads(path.read_text()); stem=safe_name(path.stem); ident=f"matcha:blessing_{stem}"
    stored=source["result"]["components"].get("minecraft:stored_enchantments",{})
    model=source["result"]["components"].get("minecraft:item_model",f"minecraft:blessing_{stem}").split(":")[-1]
    texture_source=JAVA/f"assets/minecraft/textures/item/{model}.png"
    key=f"matcha_blessing_{stem}"
    if texture_source.exists():
        shutil.copy2(texture_source,TEXTURES/f"{stem}.png"); texture=f"textures/items/generated_blessings/{stem}"
    else: texture="textures/items/book_enchanted"
    atlas["texture_data"][key]={"textures":texture}
    name=source_lang.get("item.kleispack.blessing","Blessing")+": "+path.stem.replace("_"," ").title()
    item={"format_version":"1.21.100","minecraft:item":{"description":{"identifier":ident,"menu_category":{"category":"items"}},"components":{
        "minecraft:display_name":{"value":f"item.{ident}.name"},"minecraft:icon":{"textures":{"default":key}},
        "minecraft:max_stack_size":1,"minecraft:glint":True,"minecraft:interact_button":"Apply Blessing",
        "minecraft:use_animation":"bow","minecraft:use_modifiers":{"use_duration":0.2,"movement_modifier":1.0}}}}
    (ITEMS/f"{stem}.json").write_text(json.dumps(item,indent=2)+"\n")
    recipe=json.loads(path.read_text()); recipe["result"]={"id":ident,"count":1}
    outputs=convert(recipe,"blessings",f"blessing_{stem}")
    for index,output in enumerate(outputs):
        suffix=f"_v{index+1}" if len(outputs)>1 else ""
        (RECIPES/f"{stem}{suffix}.json").write_text(json.dumps(output,indent=2)+"\n")
    blessings[ident]=dict(sorted(stored.items())); lang.append(f"item.{ident}.name={name}")

# Map custom equipment carrying upstream enchantments to scripted effects.
equipment={}
for spec_path in sorted((ROOT/"tools/equipment_tiers").glob("*.json")):
    spec=json.loads(spec_path.read_text())
    for item in spec["items"]:
        custom=sorted(k.split(":",1)[1] for k in item.get("source_enchantments",{}) if k.startswith("main:"))
        if custom: equipment[f"matcha:{spec['tier']}_{item['name']}"]=custom
for recipe_path in sorted((JAVA/"data").glob("*/recipe/*.json")):
    components=json.loads(recipe_path.read_text()).get("result",{}).get("components",{})
    custom=sorted(k.split(":",1)[1] for k in components.get("minecraft:enchantments",{}) if k.startswith("main:"))
    item_path=ROOT/f"behavior_pack/items/generated_components/{recipe_path.stem}.json"
    if custom and item_path.exists():
        identifier=json.loads(item_path.read_text())["minecraft:item"]["description"]["identifier"]
        equipment[identifier]=sorted(set(equipment.get(identifier,[])+custom))

data="// Generated by tools/generate_enchantments.py; do not edit.\n"
data+=f"export const BLESSINGS = {json.dumps(blessings,indent=2)};\n"
data+=f"export const EQUIPMENT_ENCHANTMENTS = {json.dumps(equipment,indent=2)};\n"
(ROOT/"behavior_pack/scripts/enchantment_data.js").write_text(data)
test=["# Hold the target item in your off hand, then use each blessing from the main hand."]
test += [f"give @s {identifier} 1" for identifier in sorted(blessings)]
(ROOT/"behavior_pack/functions/matcha_enchantment_test.mcfunction").write_text("\n".join(test)+"\n")
text=LANG.read_text(); begin="## BEGIN GENERATED MATCHA BLESSINGS"; end="## END GENERATED MATCHA BLESSINGS"
if begin in text: text=text.split(begin,1)[0].rstrip()+"\n"+text.split(end,1)[1].lstrip()
LANG.write_text(text.rstrip()+"\n\n"+begin+"\n"+"\n".join(lang)+"\n"+end+"\n")
ATLAS.write_text(json.dumps(atlas,indent=2)+"\n")
report={"baseline":baseline(),"custom_enchantments":len(list((JAVA/"data/main/enchantment").glob("*.json"))),"blessings":len(blessings),"equipment_with_embedded_effects":len(equipment),"recipe_files":len(list(RECIPES.glob("*.json"))),"application":"use blessing in main hand with target equipment in off hand"}
(ROOT/"docs/enchantment-check-report.json").write_text(json.dumps(report,indent=2)+"\n")
print(json.dumps(report))
