#!/usr/bin/env python3
"""Generate safe vanilla-to-Matcha singleton replacement tables."""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from convert_foods import custom_item_id
from convert_recipes import safe_name

EXISTING={"crystal_heart":"matcha:heart_container","bronze_sword":"matcha:bronze_sword"}

def signature(recipe:dict)->tuple[str,str]:
    components=recipe["result"]["components"]
    return recipe["result"]["id"],json.dumps(components,sort_keys=True,separators=(",",":"))

def main()->None:
    parser=argparse.ArgumentParser()
    parser.add_argument("java_root",type=Path)
    parser.add_argument("repo_root",type=Path,nargs="?",default=Path(__file__).resolve().parents[1])
    args=parser.parse_args(); root=args.repo_root.resolve(); java=args.java_root.resolve()
    sources=[]
    for path in sorted((java/"data").glob("*/recipe/*.json")):
        recipe=json.loads(path.read_text())
        if recipe.get("result",{}).get("components"):
            sources.append((path,recipe))

    signature_groups=defaultdict(list)
    for path,recipe in sources: signature_groups[signature(recipe)].append(path)
    canonical={key:min(paths,key=lambda p:("_from_" in p.stem,len(p.stem),p.stem)).stem for key,paths in signature_groups.items()}
    targets=defaultdict(set); evidence=defaultdict(list)
    for path,recipe in sources:
        components=recipe["result"]["components"]
        if "minecraft:consumable" in components or "minecraft:potion_contents" in components:
            target=custom_item_id(recipe,path)
        elif (root/"behavior_pack/items/generated_equipment"/f"{path.stem}.json").exists():
            target=f"matcha:{safe_name(path.stem)}"
        else:
            stem=canonical[signature(recipe)]
            target=EXISTING.get(stem,f"matcha:{safe_name(stem)}")
        base=recipe["result"]["id"]
        targets[base].add(target); evidence[base].append(str(path.relative_to(java)))

    replacements={base:next(iter(values)) for base,values in targets.items() if len(values)==1 and base!="minecraft:air"}
    ambiguous={base:sorted(values) for base,values in targets.items() if len(values)>1}
    payload={"description":"Survival-only canonical replacements. Ambiguous vanilla bases remain available as upgrade inputs.","replacements":dict(sorted(replacements.items())),"ambiguous":dict(sorted(ambiguous.items())),"evidence":dict(sorted(evidence.items()))}
    (root/"tools/vanilla_replacements.json").write_text(json.dumps(payload,indent=2)+"\n")
    js="// Generated by tools/generate_vanilla_replacements.py; do not edit.\nexport const VANILLA_REPLACEMENTS = "+json.dumps(payload["replacements"],indent=2)+";\n"
    (root/"behavior_pack/scripts/vanilla_replacements.js").write_text(js)
    report={"singleton_replacements":len(replacements),"ambiguous_bases":len(ambiguous),"replacements":payload["replacements"],"ambiguous":payload["ambiguous"]}
    (root/"docs/vanilla-replacement-report.json").write_text(json.dumps(report,indent=2)+"\n")
    print(json.dumps({"singleton_replacements":len(replacements),"ambiguous_bases":len(ambiguous)}))

if __name__=="__main__": main()
