#!/usr/bin/env python3
"""Generate safe vanilla-to-Matcha singleton replacement tables."""
from __future__ import annotations

import argparse
import json
from collections import defaultdict
from pathlib import Path

from convert_foods import custom_item_id
from convert_recipes import safe_name

EXISTING={"crystal_heart":"matcha:heart_container","bronze_sword":"matcha:bronze_sword"}

def same_name_matcha_item(vanilla_id:str,targets:set[str])->str|None:
    """Return the Matcha item whose path exactly matches the vanilla path."""
    vanilla_name=vanilla_id.split(":",1)[-1]
    candidate=f"matcha:{vanilla_name}"
    return candidate if candidate in targets else None

def resolve_targets(targets:dict[str,set[str]])->tuple[dict[str,str],dict[str,list[str]]]:
    replacements={}
    ambiguous={}
    for base,values in targets.items():
        if base=="minecraft:air":
            continue
        preferred=same_name_matcha_item(base,values)
        if preferred is not None:
            replacements[base]=preferred
        elif len(values)==1:
            replacements[base]=next(iter(values))
        else:
            ambiguous[base]=sorted(values)
    return replacements,ambiguous

def signature(recipe:dict)->tuple[str,str]:
    components=recipe["result"]["components"]
    return recipe["result"]["id"],json.dumps(components,sort_keys=True,separators=(",",":"))

def main()->None:
    parser=argparse.ArgumentParser()
    parser.add_argument("java_root",type=Path)
    parser.add_argument("repo_root",type=Path,nargs="?",default=Path(__file__).resolve().parents[1])
    args=parser.parse_args(); root=args.repo_root.resolve(); java=args.java_root.resolve()
    sources=[]
    for path in sorted((java/"data").glob("*/recipe/*.json")):
        recipe=json.loads(path.read_text())
        if recipe.get("result",{}).get("components"):
            sources.append((path,recipe))

    signature_groups=defaultdict(list)
    for path,recipe in sources: signature_groups[signature(recipe)].append(path)
    canonical={key:min(paths,key=lambda p:("_from_" in p.stem,len(p.stem),p.stem)).stem for key,paths in signature_groups.items()}
    targets=defaultdict(set); evidence=defaultdict(list)
    for path,recipe in sources:
        components=recipe["result"]["components"]
        if "minecraft:consumable" in components or "minecraft:potion_contents" in components:
            target=custom_item_id(recipe,path)
        elif (root/"behavior_pack/items/generated_equipment"/f"{path.stem}.json").exists():
            target=f"matcha:{safe_name(path.stem)}"
        else:
            stem=canonical[signature(recipe)]
            target=EXISTING.get(stem,f"matcha:{safe_name(stem)}")
        base=recipe["result"]["id"]
        targets[base].add(target); evidence[base].append(str(path.relative_to(java)))

    # When both namespaces expose the same item name, the Matcha definition is
    # canonical. This also resolves bases that have additional, differently
    # named Matcha variants (for example dried_kelp_from_dried_kelp_block).
    replacements,ambiguous=resolve_targets(targets)
    existing_path=root/"tools/vanilla_replacements.json"
    existing=json.loads(existing_path.read_text()) if existing_path.exists() else {}
    payload={"description":"Survival-only canonical replacements. Ambiguous vanilla bases remain available as upgrade inputs.","replacements":dict(sorted(replacements.items())),"ambiguous":dict(sorted(ambiguous.items())),"evidence":dict(sorted(evidence.items()))}
    # These overrides are curated separately from singleton discovery. Keep
    # them intact when the unified item pipeline refreshes this generated file.
    for key in ("recipe_overrides","recipe_override_sources"):
        if key in existing: payload[key]=existing[key]
    (root/"tools/vanilla_replacements.json").write_text(json.dumps(payload,indent=2)+"\n")
    js="// Generated by tools/generate_vanilla_replacements.py; do not edit.\nexport const VANILLA_REPLACEMENTS = "+json.dumps(payload["replacements"],indent=2)+";\n"
    (root/"behavior_pack/scripts/vanilla_replacements.js").write_text(js)
    report={"singleton_replacements":len(replacements),"ambiguous_bases":len(ambiguous),"replacements":payload["replacements"],"ambiguous":payload["ambiguous"]}
    (root/"docs/vanilla-replacement-report.json").write_text(json.dumps(report,indent=2)+"\n")
    print(json.dumps({"singleton_replacements":len(replacements),"ambiguous_bases":len(ambiguous)}))

if __name__=="__main__": main()
